### ISSUE TITLE
Layout of compartements is not stable in Alpha (not sure about Rel

### ISSUE THREAD

**Issue by lesloew** [virtualcell/vcell#260] opened 2022-08-11 14:48 UTC
I shared the model GeometriesForMatt with Dan. This is where this seems to happen whenever anything alese is changed in the model.

**Comment by jcschaff** [comment] 2022-08-11 16:23
many @lesloew or @danv61 can elaborate, not sure what the problem is.

**Comment by lesloew** [comment] 2022-08-11 16:34
I shared the example model with user schaff (already shared with danv). You'll see that the PostSynM and PostSyn compartments are  positioned to the right. I can move them to be adjacent to the Cleft compartment and then save. Then if I do anything else, even as simple and unrelated as changing the name of an application, when I go back to the Reaction Diagram, the compartments have  again reverted to the undesired layout.

**Comment by lesloew** [comment] 2022-08-11 17:06
Left my fuller explanation in a comment on the githhub issue. Do you get a notice automatically when I do that?
Les

**Comment by danv61** [comment] 2022-08-11 18:01
@jcschaff can you load the model at all? I get a
 org.vcell.util.DataAccessException: RPC method DbRequestQueue:getBioModelXML() failed: response status: 500

**Comment by danv61** [comment] 2022-09-07 12:45
Compartments are not reordered based on old-style topology anymore.
Fixed in commit f7fb0ef

**Closed by danv61** 2022-09-07 12:45 UTC
Labels: bug
