### ISSUE TITLE
Copy and Paste reactions doesn't work at all

### ISSUE THREAD

**Issue by lesloew** [virtualcell/vcell#504] opened 2022-10-28 01:48 UTC
This was apparently closed (#436) but it still doesn't work. I get a null pointer exception.
(Incidentally, this is a good way to get the dialog box that asks you to report the error to VCell Support)

**Comment by moraru** [comment] 2022-10-28 02:34
@lesloew yes, it was closed because it was a duplicate of #150 which is still open, see comments in #436

**Closed** 2022-10-28 02:34 UTC
Labels: bug
