### ISSUE TITLE
Enable quickrun for stochastic hybrid nonspatial solvers

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#188] opened 2022-07-19 15:02 UTC
required dependency library NetCDF

**Comment by jcschaff** [comment] 2023-11-03 22:05
this issue is related to the multi-platform build issues in the https://github.com/virtualcell/vcell-solver repo.

**Comment by jcschaff** [comment] 2023-11-03 22:07
see https://github.com/virtualcell/vcell-solvers/issues/25

**Comment by jcschaff** [comment] 2023-11-03 22:08
duplicate of https://github.com/virtualcell/vcell-solvers/issues/25

**Closed by jcschaff** 2023-11-03 22:08 UTC
Labels: enhancement, Blocked, zenhub
