### ISSUE TITLE
Legacy math for "source" reaction incompatible with current math

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#536] opened 2022-11-02 04:13 UTC
"Source" reaction of mass action type was possible to use in older versions of VCell where the forward rate was interpreted as a constant production rate (not eliminated by zero multiplier due to absence of substrate).

Reaction of type (nothing -> s1) of type MA results in rate law of (Kf - Kr * s1) in old math, which is obviously both incorrect and unexpected behavior.

Same situation results in rate law of (- Kr *s1) in current math, which is obviously correct; it is still (somewhat) unexpected behavior, but the user is warned of that and suggested to use general kinetics, not MA, for "sources".

Besides the old math being incorrect, a side product of *current* use of MA with no substrate is that Kf values are exported as local parameters instead of global parameters, and while unused, they are in fact available for overrides and not resolved if targeted for change via SBase ID (which is pointless anyway).

Additionally, this is not being caught by roundtrip validation testing and becomes apparent only by failure of reassembly into a single biomodel if a simulation override happens to target such parameter.

Example public model biomodel_2082195

**Comment by lesloew** [comment] 2022-11-02 15:49
I looked at that model in both Rel (34) and Alpha 79. When you refresh math in Rel, the following warning pops up:
Issues encountered during Math Generation:
Identifiers warning : With Mass Action kinetics, reaction 'Cyclin synthesis' will be interpreted as a degradation of the product.
Cyclin_synthesis is the reaction that is set up as a "Source" reaction. The forward rate is in the original math, but diappears in the refreshed math, as Ion said. This is not the behavior that is intended by the user. In Alpha 79, the math is refreshed exactly the same way, but no warning message is generated.

**Comment by jcschaff** [comment] 2022-11-02 16:24
### Summary of math/numerics validation in VCell.

#### new SBML/SEDMLExporter round-trip testing
- Round-trip testing of SBML/SEDML compares equivalency of freshly generated math of original published or public models, before SBML/SEDML export/import, to generated math from newly imported model.  
- This math compare was designed to validate that the SBML/SEDML export/import operation didn't change the model interpretation in a quantitative way.
- This testing has caught a lot of subtle bugs in vcell and uncovered many issues with legacy models.
- This testing is now performed on each commit

#### new SBML/SEDML execution testing
- Import and execution of COMBINE archives exercises SBML/SEDML importing and successfully invoking the solvers and collecting the designed results.  Current testing is focused on COMBINE archives which were generated with VCell.
- The actual numerical correctness of simulation results is not tested here.
- This testing has caught some bugs in vcell and uncovered issues with legacy models.
- This testing is now performed (or will be soon) every night (initiated by GitHub action and run on UCHC cluster).

#### MathVerifier compares math stored in vcell database with newly generated math using current software version
- This testing was intended to verify that the new software generates correct math (by exercising against a lot of models).
- This process of comparing against original math is more difficult because
   - over 20+ years, there have been a small number of vcell bugs in math generation which were eventually fixed:
        - so, some legacy models have wrong math descriptions stored in the VCell database (and incorrect simulation results stored in our file server).
   - over 20+ years, the style of math generation has changed a bit and it is sometimes difficult for the math comparison algorithm to correctly compare old style and new style math descriptions.
- This testing was traditionally performed very rarely (at most once or twice a year).  I don't know when it was last run.

#### MathTestingFramework: an end-to-end quantitative regression test for biomodel/mathmodel simulation results.
- A test suite of ~100-200 public/published and interesting models where chosen to represent a good cross section of VCell features. 
- Loads each original model in suite, regenerates math, re-saves each model, loads models back in, runs simulations, reads original results, read new results, compare results).
- model test suites (models and results) are stored in vcell database (user vcelltestaccount).
- each simulation has a quantitative pass/fail criteria - but there are false negatives which must be manually curated.
- This testing was performed before each major release (at most one or two times per year).  I don't know when the last run was.

#### StochtestRunService/StochasticCompareService framework for stochastic cross-validation testing.
- Designed to cross-validate the stochastic predictions statistically against equivalent models/solvers.
- compared predictions for same model with equivalent applications: rule-based NFSim, network-based SSA, network-spatial Smoldyn, and network-determinstic CVODE. 
- was run against a large number of models from VCell database.
- identified several bugs and proved correctness of stochastic models/simulations
- This testing was only performed once many years ago.

**Comment by jcschaff** [comment] 2022-11-02 16:52
### Testing strategy

#### Test/Improve the Software
In the past we focused on the software:  most of our testing has been concerned with validating and improving the VCell software - and notifying users if any of their models were found to be impacted by previous bugs.

#### Verify/Repair the public/published models for public consumption
- can we rerun all of the simulations?
- are the maths correct and equivalent (were they correct originally, are they correct now).
- if there was stored simulation results, are the newly generated simulation results equivalent? 
- if there are no simulation results stored for these models, we can run these models now so users can browse the simulation results.

#### Next steps for public model validation

1. rerun a version of MathVerifier against all public models
2. manually curate failures (some maths may be equivalent, but the automated comparison algorithm isn't smart enough).
3. for those models that have equivalent math but missing results, rerun the simulations and populate the results.
4. for those models (or classes of models) which had problems - propose what to do next.

**Comment by lesloew** [comment] 2022-11-02 16:56
Should we manually curate biomodel_2082195 (and others that use MA for a Source reaction) to convert that reaction from MA to General, so the intent of the user is preserved?

**Comment by jcschaff** [comment] 2022-11-02 17:04
Probably ...However,  in that case, the new GeneralKinetics rate expression would still be weird "kf - Kr * s1".

**Comment by jcschaff** [comment] 2023-02-01 14:47
query to find candidate models which may have this problem (280 BioModels):

select reactionId, reactants1, products1, kinetics
from (select VC_REACTSTEP.ID                                       as reactionId,
             VC_REACTSTEP.KINETICSSML                              as kinetics,
             SUM(case when VR.ROLE = 'reactant' then 1 else 0 end) as reactants1,
             SUM(case when VR.ROLE = 'product' then 1 else 0 end)  as products1
      from VC_REACTSTEP
               join VC_REACTPART VR on VC_REACTSTEP.ID = VR.REACTSTEPREF
      where VC_REACTSTEP.KINETICSSML like '%MassActionKinetics%'
        and VC_REACTSTEP.KINETICSSML not like '%Parameter Kf 0.0%'
      group by VC_REACTSTEP.ID, VC_REACTSTEP.KINETICSSML)
where reactants1 = 0
  and products1 > 0;

**Comment by jcschaff** [comment] 2023-02-01 20:23
### Background
* non-zero mass action Kf parameters should have been ignored if no reactants (zero-order source term).
* non-zero mass action Kr parameters should have been ignored if no products (zero-order degradation term).
* early versions of VCell treated these parameters as constant terms (e.g. Kf * Product_of(reactants_i) -> Kf, if no reactants)
* recent versions of VCell ignore these non-zero parameter terms as violating the expected semantics of "Mass Action" kinetics from Chemistry (and a warning is presented to the user).

### Strategy
Transform the legacy BioModel as needed to preserve the original intent of the legacy models (should be mathematically equivalent)
1. if the parameter WAS used as a source term in any math description - then convert the kinetic law to GeneralKinetics and preserve the math.
2. if the parameter WAS NOT used as a source term in any math description - then set it to 0.0

**Closed** 2023-02-02 06:41 UTC
Labels: bug, type: epic, VCell-7.5.0, VCell-7.6.0, validation
